# Generated by Django 2.2.6 on 2019-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20191017_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cabina',
            field=models.IntegerField(default='1', help_text='Cantidad de asientos', max_length=1),
        ),
    ]
