# Generated by Django 2.2.6 on 2019-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20191018_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cabina',
            field=models.IntegerField(default='1', help_text='Cantidad de asientos'),
        ),
    ]
