# Generated by Django 2.2.6 on 2019-10-18 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20191018_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cabina',
            field=models.IntegerField(default='1', help_text='Cantidad de asientos', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
