# Generated by Django 2.2.6 on 2019-11-15 20:20

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20191018_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='descripcion',
            field=models.TextField(default='Vacio', help_text='Una breve descripcion', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='modificado_el',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='resena',
            field=models.TextField(help_text='Explayate al describir sobre el vehiculo', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='valor',
            field=models.IntegerField(default='1', help_text='Valor del vehiculo en USD', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='auto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
