# Generated by Django 2.2.6 on 2019-11-26 19:58

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='autor',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
